name: Handle Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r23

      - name: Build binaries and compress them
        run: |
          ./.github-deps/change-settings.ps1 -params @{STATIC_BUILD="false"; BUILD_MAGICKPP="true"; HDRI_ENABLE= "false"; QUANTUM_DEPTH= "8"}
          ./build-release
          Compress-Archive -CompressionLevel Optimal -Path "jniLibs/arm64-v8a" -DestinationPath "imagemagick-7-android-Q8-shared.zip"
          rm -r jniLibs
          
          ./.github-deps/change-settings.ps1 -params @{STATIC_BUILD="false"; BUILD_MAGICKPP="true"; HDRI_ENABLE= "true"; QUANTUM_DEPTH= "8"}
          ./build-release
          Compress-Archive -CompressionLevel Optimal -Path "jniLibs/arm64-v8a" -DestinationPath "imagemagick-7-android-Q8-HDRI-shared.zip"
          rm -r jniLibs
          
          ./.github-deps/change-settings.ps1 -params @{STATIC_BUILD="false"; BUILD_MAGICKPP="true"; HDRI_ENABLE= "false"; QUANTUM_DEPTH= "16"}
          ./build-release
          Compress-Archive -CompressionLevel Optimal -Path "jniLibs/arm64-v8a" -DestinationPath "imagemagick-7-android-Q16-shared.zip"
          rm -r jniLibs
          
          ./.github-deps/change-settings.ps1 -params @{STATIC_BUILD="false"; BUILD_MAGICKPP="true"; HDRI_ENABLE= "true"; QUANTUM_DEPTH= "16"}
          ./build-release
          Compress-Archive -CompressionLevel Optimal -Path "jniLibs/arm64-v8a" -DestinationPath "imagemagick-7-android-Q16-HDRI-shared.zip"
          rm -r jniLibs

      - name: Create Release
        uses: ncipollo/release-action@v1.11.1
        with:
          artifacts: "jniLibs/arm64-v8a/*.zip"
          allowUpdates: true
          tag: ImageMagick7-Android
